// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramBot.DAL.Contexts;

#nullable disable

namespace TelegramBot.DAL.Migrations.Postgres
{
    [DbContext(typeof(TelegramPostgresDbContext))]
    partial class TelegramPostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramBot.DAL.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool?>("CanSetStickerSet")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("InviteLink")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("SlowModeDelay")
                        .HasColumnType("integer");

                    b.Property<string>("StickerSetName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Chats", "public");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.ChatPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("CanAddWebPagePreviews")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanChangeInfo")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanInviteUsers")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanPinMessages")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanSendMediaMessages")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanSendMessages")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanSendOtherMessages")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanSendPolls")
                        .HasColumnType("boolean");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("Id", "ChatId")
                        .IsUnique();

                    b.ToTable("ChatPermissions", "public");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Contact", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Vcard")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "UserId")
                        .IsUnique();

                    b.ToTable("Contacts", "public");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorSignature")
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<bool?>("ChannelChatCreated")
                        .HasColumnType("boolean");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConnectedWebsite")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("DeleteChatPhoto")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ForwardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ForwardFromMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("ForwardSenderName")
                        .HasColumnType("text");

                    b.Property<string>("ForwardSignature")
                        .HasColumnType("text");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("GroupChatCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaGroupId")
                        .HasColumnType("text");

                    b.Property<long?>("MigrateFromChatId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MigrateToChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewChatTitle")
                        .HasColumnType("text");

                    b.Property<long?>("PreviousMessageId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("SupergroupChatCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages", "public");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Update", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("Updates", "public");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool?>("CanJoinGroups")
                        .HasColumnType("boolean");

                    b.Property<bool?>("CanReadAllGroupMessages")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool?>("SupportsInlineQueries")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.ChatPermission", b =>
                {
                    b.HasOne("TelegramBot.DAL.Entities.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Contact", b =>
                {
                    b.HasOne("TelegramBot.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Message", b =>
                {
                    b.HasOne("TelegramBot.DAL.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TelegramBot.DAL.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Update", b =>
                {
                    b.HasOne("TelegramBot.DAL.Entities.Message", "Message")
                        .WithOne("Update")
                        .HasForeignKey("TelegramBot.DAL.Entities.Update", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.Message", b =>
                {
                    b.Navigation("Update");
                });

            modelBuilder.Entity("TelegramBot.DAL.Entities.User", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
