CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE public."Chats" (
    "Id" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "Type" integer NOT NULL,
    "Title" text NULL,
    "Username" text NULL,
    "FirstName" text NULL,
    "LastName" text NULL,
    "Description" text NULL,
    "InviteLink" text NULL,
    "SlowModeDelay" integer NULL,
    "StickerSetName" text NULL,
    "CanSetStickerSet" boolean NULL,
    CONSTRAINT "PK_Chats" PRIMARY KEY ("Id")
);

CREATE TABLE public."Users" (
    "Id" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "IsBot" boolean NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NULL,
    "UserName" text NULL,
    "LanguageCode" text NULL,
    "CanJoinGroups" boolean NULL,
    "CanReadAllGroupMessages" boolean NULL,
    "SupportsInlineQueries" boolean NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE public."ChatPermissions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "CanSendMessages" boolean NULL,
    "CanSendMediaMessages" boolean NULL,
    "CanSendPolls" boolean NULL,
    "CanSendOtherMessages" boolean NULL,
    "CanAddWebPagePreviews" boolean NULL,
    "CanChangeInfo" boolean NULL,
    "CanInviteUsers" boolean NULL,
    "CanPinMessages" boolean NULL,
    "ChatId" bigint NOT NULL,
    CONSTRAINT "PK_ChatPermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatPermissions_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES public."Chats" ("Id") ON DELETE CASCADE
);

CREATE TABLE public."Contacts" (
    "Id" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "PhoneNumber" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NULL,
    "Vcard" text NULL,
    "UserId" bigint NOT NULL,
    CONSTRAINT "PK_Contacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contacts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE public."Messages" (
    "Id" bigint NOT NULL,
    "PreviousMessageId" bigint NULL,
    "Caption" text NULL,
    "NewChatTitle" text NULL,
    "DeleteChatPhoto" boolean NULL,
    "GroupChatCreated" boolean NULL,
    "SupergroupChatCreated" boolean NULL,
    "ChannelChatCreated" boolean NULL,
    "MigrateToChatId" bigint NULL,
    "MigrateFromChatId" bigint NULL,
    "ConnectedWebsite" text NULL,
    "FromUserId" bigint NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "ForwardFromMessageId" integer NULL,
    "ForwardSignature" text NULL,
    "ForwardSenderName" text NULL,
    "ForwardDate" timestamp with time zone NULL,
    "EditDate" timestamp with time zone NULL,
    "MediaGroupId" text NULL,
    "AuthorSignature" text NULL,
    "Text" text NOT NULL,
    "Type" integer NOT NULL,
    "UserId" bigint NOT NULL,
    "ChatId" bigint NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Chats_ChatId" FOREIGN KEY ("ChatId") REFERENCES public."Chats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE public."Updates" (
    "Id" bigint NOT NULL,
    "Type" integer NOT NULL,
    "MessageId" bigint NOT NULL,
    CONSTRAINT "PK_Updates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Updates_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES public."Messages" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatPermissions_ChatId" ON public."ChatPermissions" ("ChatId");

CREATE UNIQUE INDEX "IX_ChatPermissions_Id_ChatId" ON public."ChatPermissions" ("Id", "ChatId");

CREATE INDEX "IX_Chats_Id" ON public."Chats" ("Id");

CREATE INDEX "IX_Contacts_Id" ON public."Contacts" ("Id");

CREATE UNIQUE INDEX "IX_Contacts_Id_UserId" ON public."Contacts" ("Id", "UserId");

CREATE INDEX "IX_Contacts_UserId" ON public."Contacts" ("UserId");

CREATE INDEX "IX_Messages_ChatId" ON public."Messages" ("ChatId");

CREATE INDEX "IX_Messages_Id" ON public."Messages" ("Id");

CREATE INDEX "IX_Messages_UserId" ON public."Messages" ("UserId");

CREATE INDEX "IX_Updates_Id" ON public."Updates" ("Id");

CREATE UNIQUE INDEX "IX_Updates_MessageId" ON public."Updates" ("MessageId");

CREATE INDEX "IX_Users_Id" ON public."Users" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220514163339_InitialCreate', '6.0.5');

COMMIT;

